### ISSUE TITLE
Dashboard Page Improvements

### ISSUE THREAD

**Issue by FifthSurprise** [MegaGameSociety/WatchTheSkiesDashboard#17]
Please make the following improvements to the Watch the Skies Dashboard:

*  The Rioter Count Font needs to be bigger or possibly improved.  Maybe with some sort of graphic I can repeat per rioter with a + if we hit greater than say... 10.
*  The Activity Font text should be bigger.  In general, this text field doesn't serve much purpose since it's only being entered in by Military Control.  News players should be handling this so we should move it somewhere else.  Likewise the message from Control at the top is too small and gets missed.
*  Terror Tracker should be something better than a fraction (possibly a graphic like the bootstrap progress bar).  This should be more centered as it's the most important thing besides the Round countdown timer.
*  I changed News so that it's a constantly changing divs.  This is different from the LI structure which we had before (which frankly, I like a lot better but didn't have time to get the css to jive well with Angular).  I would like a second pair of eyes on it to ensure to see I didn't break anything too much.

**Comment by michaelpelletier** [comment]
:+1: I'm back in the hospital tomorrow for some more tests, but fingers crossed that I can get to this stuff by this weekend.

**Comment by FifthSurprise** [comment]
@michaelpelletier Please take the time to take care of yourself.  I'm just writing all of this down as things I observed during the Bethpage game and would like to write down.

**Comment by michaelpelletier** [comment]
Closed with https://github.com/MegaGameSociety/WatchTheSkiesDashboard/issues/24
