### ISSUE TITLE
Dashboard Clock

### ISSUE THREAD

**Issue by FifthSurprise** [MegaGameSociety/WatchTheSkiesDashboard#2]
Requirement:  A Javascript visual clock that will let players know how much time until the next round.

Ideally, this would be a flipdown clock like [FlipClock](http://flipclockjs.com/). Flipclock might be an appropriate JS library but any version is acceptable.  Please investigate as to whether D3 is appropriate for this work.

Input would be from an AJAX call that updates the scope with the next round's time and whether the game is currently paused.

-  The clock needs to count-down until the next time.
-  It should be in terms of minutes / seconds
-  If the round is paused, the clock should not flipdown.
-  If the clock hits 0, it should not go back to the next round until it receives a new next round time
-  This clock will reside on the dashboard and will be incorporated into the design of the front-end page.

**Comment by justcolin** [comment]
I'll work on it this week.

**Comment by FifthSurprise** [comment]
As discussed, please assume you are receiving the following information in a json request:

-  The time the next round starts (UTC)
-  The current round # 
-  Whether the round is paused.

**Comment by justcolin** [comment]
That'll work perfectly. Aren't you also sending the current global terror state and any news stories for display? Am I missing anything else?

It would be good to get all of the game state in one JSON response which all client applications can use. For example: if the global game state JSON object contains all the news stories in an array in chronological order the dashboard can pick off the most recent one (or whichever ones have a "show in dashboard" flag set), while the iOS application can display all of them with time stamps.

The global terror level should be sent with the current terror number, the maximum value the terror tracker can reach, and a boolean for whether the global terror is above the danger threshold. That way the server and dashboard code won't both have to be updated if the rules change, and you won't have to send anything else if the designer decides to change how the global terror is displayed (like if they decide to go from showing a percentage to the exact fraction).

**Comment by FifthSurprise** [comment]
These are good ideas and I'll incorporate them into the JSON object that gets sent out.

**Comment by justcolin** [comment]
@FifthSurprise: Here is the JSON object formatting I have been working with. I tried to make sure it is easy to extend if/when we want to add more data to the various items. Let me knows if you have any problems with this.
```
{
  "timer": {
    "round":  INT,
    "start":  INT, // Unix time stamp
    "paused": BOOL,
  },

  "global_terror": {
    "terror_level":  INT,
    "terror_max":    INT,
    "terror_danger": STRING, // "fine" | "warn" | "alert"
    "riot_count":    INT
  },

  "news": {
    "feed": [
      {
        "title":  STRING,
        "source": STRING,
        "body":   STRING
      },
      {
        "title":  STRING,
        "source": STRING,
        "body":   STRING
      }
      // Etc, in chronological order
    ]
  }

  "messages": [
    "feed": [
      {
        "title":  STRING,
        "body":   STRING
      },
      {
        "title":  STRING,
        "body":   STRING
      }
      // Etc, in chronological order
    ]
  ]
}

```

**Comment by FifthSurprise** [comment]
Riot_count is the # of rioters right?

Otherwise, this looks fine to me.

**Comment by justcolin** [comment]
Yup!

**Comment by justcolin** [comment]
Since FlipClock.js is being annoying for our needs and adds jQuery as a dependency I am currently mucking about with a pure CSS FlipClock that we can directly plumb into Angular.

**Comment by CalixJumi** [comment]
Hello!, for the json stuff we usually add this kind of generic header(?):

{
  "status" : int 
  "message" : STR (always useful)
  "date" : date

  "result": {  //The meat
        "timer" :  stuff
        "news" :
        "messages" : etc  
    },

}

This has been useful to me when implementing global modifications to the web services and devices, its just a little layer that separates the global functionalities of every web service against the specific ones of each view. (ie we used it to present an alertview, log out or move the user to another view, refresh globally, its a cheap approach to lack of push notifications :P )

I just have a single question but its about the definition/rules i might not know,
Paused means the timer is paused or that the next game will not start until unpaused?, or how do that works?, the time left should be calculated by  [15 min - (current time - started time)]?

**Comment by FifthSurprise** [comment]
Paused means timer is paused.  Which means the time until the next round starts is unknown until the round is unpaused.

Generally what I see happening is the time is paused because something happened, then user figures out when they want the next round to begin, changes start time accordingly ("start" being the time the next round starts), and then unpauses.

**Comment by CalixJumi** [comment]
Ohh I see.. so a simple time left  = start time - current time, right? okey dokey

**Comment by justcolin** [comment]
We need to add a field to the 'timer' data in the JSON request which is call 'length'. It will have an in which is the total number of seconds the current round will last.

The client side app will start a timer when the round starts. It will be set to last for the 'length' in the JSON response. It will pause when 'paused' is TRUE. If you want to extend the current round, update the int in 'length' and the client side app will update the timer to read as 'length' minus the elapsed number of seconds.

**Comment by justcolin** [comment]
I also have no qualms with adding that header info to the response. A little more metadata always helps.

**Comment by FifthSurprise** [comment]
I've started digging into writing an API JSON endpoint for dashboard data.

I do not think we should implement the timer through JSON calls.  Essentially, there should just be a unix time past on as to when the next round is going to start.  Then you can calculate from current time  (either from client side or you can just use what was passed along in the message) to figure out the length.

The reason is, we'll be sending a new length every like 3 seconds every time the front-end pings the server and that'll be prone to a lot of changes, especially because the round tends to get extended frequently by Control (by like 5 minutes or 10 minutes).

To that end, I am writing timer data to look like:
```"timer" => {
          "round"=>  @game.round,
          "next_round" =>  @game.next_round,
          "paused" => @data['paused'],
        }```

**Comment by justcolin** [comment]
If that's the case (which is perfectly okay in my book) do we really need data for a pause?

With this setup, if there is a pause the next round time doesn't nessesarily change. If that happens, when the clock is unpaused it will jump ahead by however much time it was paused for. Will the backend enforce updating the next round times to match pauses? Another option is to get rid of the idea of pauses and just extend the round my moving the end of round time. The dashboard could even add a little note if it sees the round time changed to say "10 minutes added" so players know why the timer just got extended.

**Comment by FifthSurprise** [comment]
I still want a paused boolean so that it makes it easier to just hide the clock to show that the round is paused?

However, I do like the idea of having a note for adding more time due to an extension.  Not sure how I want to implement that back-end but that would be nifty.

Also, yes, the backend will enforce updating the next round times to match pausetime.  So from front-end point of view, you just want to make sure the clock is in sync with what back-end is sending to you via json request.

Unrelated, can you confirm the version of angular you wrote the code in?  I'm going to set up angular in the application today or tomorrow and want to remain consistent.
