### ISSUE TITLE
Add Newspaper Print.css

### ISSUE THREAD

**Issue by michaelpelletier** [MegaGameSociety/WatchTheSkiesDashboard#26]
Once @FifthSurprise adds some data to the seed file to create the tweets / populate the newspaper, will need to make a print css file so that it... prints as a newspaper.

**Comment by FifthSurprise** [comment]
Some notes with regards to it:

It should ideally be a one-pager (or two-pager) in landscape.

The top images are just the images from the various news organizations.  Feel free to mess with them so they are smaller vertically (which would give us more print space).

The font choices are on purpose to show a difference between the three org. style-wise (ie. one is stuffy, one is silly aka Comic Sans, and one is modern professional).  Feel free to mess with different fonts of course but that's the reasoning for the difference.
