### ISSUE TITLE
Splash Page Design

### ISSUE THREAD

**Issue by FifthSurprise** [MegaGameSociety/WatchTheSkiesDashboard#41]
We need a splash page.

- [ ] Splash page design
- [ ] Links to login/logout (or space to do the same)
- [ ] When logged in, need space for menu of what user has access to (ie. 'home')
- [ ] When this is implemented, we also need to update dashboard to have a link to splash page

This does not cover backend requirements for checking logging in, dynamically generating the menu, or access.  This is just front-end design.

**Comment by michaelpelletier** [comment]
This be done, yo.
