### ISSUE TITLE
Updating Dashboard Gamedata

### ISSUE THREAD

**Issue by FifthSurprise** [MegaGameSociety/WatchTheSkiesDashboard#7]
Relevant Game Data should be on the Dashboard.  It should update whenever we query the database.

Please do not directly edit with JQuery or something similar since we will be frequently adjusting variables.

Best way to handle this is either ReactJS or AngularJS to take json update accordingly.

This should not include Game time related stuff which is under #2 Dashboard Clock.

**Comment by justcolin** [comment]
As discussed with @FifthSurprise , I am working on a small AngularJS one page application that will take in get the game state data (timer info, terror state, news stories, etc) in a JSON object periodically and update a view which can be styled however the designer sees fit.

**Comment by justcolin** [comment]
As mentioned on the dashboard clock issue thread, the JSON formatting I am working with is as follows:
```
{
  "timer": {
    "round":  INT,
    "start":  INT, // Unix time stamp
    "paused": BOOL,
  },

  "global_terror": {
    "terror_level":  INT,
    "terror_max":    INT,
    "terror_danger": STRING, // "fine" | "warn" | "alert"
    "riot_count":    INT
  },

  "news": {
    "feed": [
      {
        "title":  STRING,
        "source": STRING,
        "body":   STRING
      },
      {
        "title":  STRING,
        "source": STRING,
        "body":   STRING
      }
      // Etc, in chronological order
    ]
  }

  "messages": [
    "feed": [
      {
        "title":  STRING,
        "body":   STRING
      },
      {
        "title":  STRING,
        "body":   STRING
      }
      // Etc, in chronological order
    ]
  ]
}
```

**Comment by justcolin** [comment]
See the thread on issue #2 (Dashboard Clock) for some updates.

**Comment by FifthSurprise** [comment]
Completed.
