### ISSUE TITLE
Basic Messaging

### ISSUE THREAD

**Issue by FifthSurprise** [MegaGameSociety/WatchTheSkiesDashboard#8]
Create basic messaging between Humans and aliens tied to the Game.

Specifically we need a new table for the messages.

The sender (meaning a player nation or the aliens who will be treated as a country) should be stored along with the message. Right now, make all communication "public" on the Humans or the Aliens pages (we will cut this down later by assigning country/alien roles to users and filtering server-side). In other words all communications is completely open and available to anyone as long as you know the url.

This should just be standard get/post stuff. Nothing too fancy.

1.  Add migrations for a Messages table.
The table should include sender, recipient, timestamp, round number, game id, and the message.
2.  Create route/controller methods for creating a new message based on the above.
3.  Create a route, controller methods for viewing all messages so far along in order of timestamp with all available table data.

**Comment by CesarDominguez** [comment]
For the mobile app it could use push/silent notifications, its supposed to be straightforward from the back end side. However as you guys said this might detract the experience to focus on the phone, so if its possible to send (and I know is kinda ridiculous) audio files as messages (even if its f***ing slow) im sure it could enable some sort of cool stuff, like those noisy messages from the aliens, at least it applies on messages to scientist isnt it?

**Comment by michaelpelletier** [comment]
I dig the idea of audio messages. And I don't think sending them would be a particular problem, since most of them shouldn't be too long?

Something I saw in the Shut Up and Sit Down game was that (at least early on?) there were some communication _issues_ between people and aliens, so only fractions of a message got through. It probably wouldn't be hard to run the audio through some kind of filter. 

The big problem that I suspect would occur with this is actually the level of background noise.

**Comment by FifthSurprise** [comment]
I will spin off another ticket for mobile development requirements for messaging.  Consequently, I'm going to ask that we take such discussion there.  I like the idea, but unfortunately I do not think we have time.  Therefore we should implement just basic text messaging first.

**Comment by TheJhyde** [comment]
I've uploaded the code for the message system. Let me know if there's any problems with it.

**Comment by CalixJumi** [comment]
well done!, now... how should the app use the web service? pls :D or maybe post a sample url with a json in it to start testing.
